<?php

namespace MB\Proxy\Entity\__CG__\MB\Glor;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Post extends \MB\Glor\Post implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getAuthor()
    {
        $this->__load();
        return parent::getAuthor();
    }

    public function setAuthor($fromChar)
    {
        $this->__load();
        return parent::setAuthor($fromChar);
    }

    public function getAdressat()
    {
        $this->__load();
        return parent::getAdressat();
    }

    public function setAdressat($toChar)
    {
        $this->__load();
        return parent::setAdressat($toChar);
    }

    public function getPostDate()
    {
        $this->__load();
        return parent::getPostDate();
    }

    public function setPostDate($postDate)
    {
        $this->__load();
        return parent::setPostDate($postDate);
    }

    public function getMessage()
    {
        $this->__load();
        return parent::getMessage();
    }

    public function setMessage($message)
    {
        $this->__load();
        return parent::setMessage($message);
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function addComment(\MB\Glor\Post $comment)
    {
        $this->__load();
        return parent::addComment($comment);
    }

    public function getParentPost()
    {
        $this->__load();
        return parent::getParentPost();
    }

    public function setParentPost($parentPost)
    {
        $this->__load();
        return parent::setParentPost($parentPost);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'postDate', 'message', 'id', 'author', 'adressat', 'comments', 'parentPost');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}