<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121227221318CreateLocations extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE journal (id INT AUTO_INCREMENT NOT NULL, post_id INT DEFAULT NULL, loc_id VARCHAR(255) DEFAULT NULL, char_id INT DEFAULT NULL, posted DATETIME NOT NULL, type SMALLINT NOT NULL, UNIQUE INDEX UNIQ_C1A7E74D4B89032C (post_id), UNIQUE INDEX UNIQ_C1A7E74D6505CAD1 (loc_id), UNIQUE INDEX UNIQ_C1A7E74D3FF12EF9 (char_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74D4B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74D6505CAD1 FOREIGN KEY (loc_id) REFERENCES locations (loc_id)");
        $this->addSql("ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74D3FF12EF9 FOREIGN KEY (char_id) REFERENCES chars (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE journal");
    }
}
