<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121227225044UpdatesLinks extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE journal DROP INDEX UNIQ_C1A7E74D6505CAD1, ADD INDEX IDX_C1A7E74D6505CAD1 (loc_id)");
        $this->addSql("ALTER TABLE journal DROP INDEX UNIQ_C1A7E74D3FF12EF9, ADD INDEX IDX_C1A7E74D3FF12EF9 (char_id)");
        $this->addSql("ALTER TABLE journal DROP FOREIGN KEY FK_C1A7E74D3FF12EF9");
        $this->addSql("ALTER TABLE journal DROP FOREIGN KEY FK_C1A7E74D6505CAD1");
        $this->addSql("ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74D3FF12EF9 FOREIGN KEY (char_id) REFERENCES chars (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74D6505CAD1 FOREIGN KEY (loc_id) REFERENCES locations (loc_id) ON DELETE CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE journal DROP INDEX IDX_C1A7E74D6505CAD1, ADD UNIQUE INDEX UNIQ_C1A7E74D6505CAD1 (loc_id)");
        $this->addSql("ALTER TABLE journal DROP INDEX IDX_C1A7E74D3FF12EF9, ADD UNIQUE INDEX UNIQ_C1A7E74D3FF12EF9 (char_id)");
        $this->addSql("ALTER TABLE journal DROP FOREIGN KEY FK_C1A7E74D6505CAD1");
        $this->addSql("ALTER TABLE journal DROP FOREIGN KEY FK_C1A7E74D3FF12EF9");
        $this->addSql("ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74D6505CAD1 FOREIGN KEY (loc_id) REFERENCES locations (loc_id)");
        $this->addSql("ALTER TABLE journal ADD CONSTRAINT FK_C1A7E74D3FF12EF9 FOREIGN KEY (char_id) REFERENCES chars (id)");
    }
}
